server:
  port: 8181
  servlet:
    context-path: /myapp

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul
    username: java
    password: java

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml